### ISSUE TITLE
Able to proceed with no twib type selected on filter page

### ISSUE THREAD

**Issue by shinyamamotowag** [tw-inc/twibs#1]
![image](https://user-images.githubusercontent.com/37083032/124331618-6abd9300-db44-11eb-9dfb-c215ff0c4e37.png)

STR
1. Tap on the filter icon on the map view
2. Unselect all twib types
3. Hit Done CTA
4. Observe user sees the "please select at least one twib type" error but can leave the filter page

**Comment by wadamomo** [comment]
resolved
