### ISSUE TITLE
Name and birthdate can be removed from profile but still shows cached (?) age

### ISSUE THREAD

**Issue by shinyamamotowag** [tw-inc/twibs#4]
![image](https://user-images.githubusercontent.com/37083032/124332248-e79d3c80-db45-11eb-9269-0a4644fb383a.png)

1. Navigate to your profile
2. Edit name and birthdate 
3. Remove both fields
4. Observe name is removed but age shows even when birthdate is removed

![image](https://user-images.githubusercontent.com/37083032/124332356-2632f700-db46-11eb-9cd2-648145e5a975.png)

**Comment by wadamomo** [comment]
resolved
